services:
  - type: web
    name: n8n
    env: docker
    plan: starter
    envVars:
      - key: N8N_BASIC_AUTH_ACTIVE
        value: true
      - key: N8N_BASIC_AUTH_USER
        value: balvesdeoliveira3@gmail.com
      - key: N8N_BASIC_AUTH_PASSWORD
        value: n8n2025B
      - key: N8N_HOST
        value: n8n.onrender.com
      - key: N8N_PORT
        value: 5678
      - key: WEBHOOK_TUNNEL_URL
        value: https://n8n.onrender.com

